---
- name: Make config dir
  file:
    path: /etc/rest-server
    state: directory
    owner: root
    group: root
    mode: '0750'
  become: yes

- name: Add users to a password file and ensure permissions are set
  htpasswd:
    path: /etc/rest-server/.htpasswd
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    crypt_scheme: ldap_sha1
    owner: root
    group: root
    mode: 0640
  loop: "{{ rest_server_users }}"

- name: Create a network
  docker_network:
    name: rest-server-net

- name: Create rest-server container
  docker_container:
    name: restserver
    image: restic/rest-server:{{ rest_server_version }}
    ports:
      - "127.0.0.1:8010:8000"
    recreate: yes
    env:
      DISABLE_AUTHENTICATION: "1"
      OPTIONS: "{{ rest_server_options }}"
    purge_networks: yes
    volumes:
      - "{{ rest_server_datapath }}:/data"
      - /etc/rest-server/.htpasswd:/data/.htpasswd
    networks:
      - name: rest-server-net
